site_name: Project Name
repo_url: https://github.com/user/project
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - search.suggest
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: dark-theme
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: light-theme
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
markdown_extensions:
  - tables
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
nav:
  - Home: README.md
  - Browser support: browser-support.md
  - Customization: customization.md
  - License: license.md
  - Installation: fake.md
  - Creating your site: fake.md
  - Publishing your site: fake.md
  - Alternatives: fake.md
  - Changelog:
    - changelog/fake.md
    - How to upgrade: fake.md